### ISSUE TITLE
Eddystone

### ISSUE THREAD

**Issue by JosefJezek** [NordicSemiconductor/Android-nRF-Beacon#1]
Please add support for Eddystone protocol.

https://github.com/google/eddystone

**Comment by philips77** [comment]
Hi, recently we've added Eddystone support to nRF Master Control Panel app, where you can scan and read data. In nRF Beacon I'd use the Nearby API, I suppose. I'm not quite sure yet what are the features of this API. I think it's a matter of time before we will add it.

**Comment by JosefJezek** [comment]
Please add support for configuration mode of Eddystone.
- https://github.com/google/eddystone/blob/master/eddystone-url/docs/config-service-spec.md
- https://github.com/google/eddystone/tree/master/eddystone-uid

**Comment by philips77** [comment]
Before we modify the nRF Beacon app you may use [nRF Master Control Panel](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp) app. In order to assign a shortened URL we recommend using the [Physical Web](https://play.google.com/store/apps/details?id=physical_web.org.physicalweb) application which does it automatically.

**Comment by JosefJezek** [comment]
Thank you for info

**Comment by nicholasalevras** [comment]
Will this allow me to make my generic beacons compatible with Eddystone?

**Comment by purirohan** [comment]
hi has this been addressed in this app yet? Or are we to use the nRF Beacon for Eddystone app?

**Comment by roshanrajaratnam** [comment]
@nicholasalevras @purirohan Hi as of now this app will not support the eddystone configuration. Please use the nRf Beacon for Eddystone app for configuring eddystone beacons.
